/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as Context from "./graphql/context"
import { core } from "@nexus/schema"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * The `Upload` scalar type represents a file upload.
     */
    Upload<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "Upload";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * The `Upload` scalar type represents a file upload.
     */
    Upload<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "Upload";
  }
}
declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BudgetId_label_idxCompoundUniqueInput: { // input type
    budgetId: number; // Int!
    label: string; // String!
  }
  DateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  DateTimeNullableFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeNullableFilter'] | null; // NestedDateTimeNullableFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  FloatFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Float
    divide?: number | null; // Float
    increment?: number | null; // Float
    multiply?: number | null; // Float
    set?: number | null; // Float
  }
  FloatFilter: { // input type
    equals?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: number[] | null; // [Float!]
    lt?: number | null; // Float
    lte?: number | null; // Float
    not?: NexusGenInputs['NestedFloatFilter'] | null; // NestedFloatFilter
    notIn?: number[] | null; // [Float!]
  }
  FloatNullableFilter: { // input type
    equals?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: number[] | null; // [Float!]
    lt?: number | null; // Float
    lte?: number | null; // Float
    not?: NexusGenInputs['NestedFloatNullableFilter'] | null; // NestedFloatNullableFilter
    notIn?: number[] | null; // [Float!]
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedDateTimeNullableFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeNullableFilter'] | null; // NestedDateTimeNullableFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedFloatFilter: { // input type
    equals?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: number[] | null; // [Float!]
    lt?: number | null; // Float
    lte?: number | null; // Float
    not?: NexusGenInputs['NestedFloatFilter'] | null; // NestedFloatFilter
    notIn?: number[] | null; // [Float!]
  }
  NestedFloatNullableFilter: { // input type
    equals?: number | null; // Float
    gt?: number | null; // Float
    gte?: number | null; // Float
    in?: number[] | null; // [Float!]
    lt?: number | null; // Float
    lte?: number | null; // Float
    not?: NexusGenInputs['NestedFloatNullableFilter'] | null; // NestedFloatNullableFilter
    notIn?: number[] | null; // [Float!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NullableDateTimeFieldUpdateOperationsInput: { // input type
    set?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  NullableFloatFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Float
    divide?: number | null; // Float
    increment?: number | null; // Float
    multiply?: number | null; // Float
    set?: number | null; // Float
  }
  NullableStringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  QueryBudgetsWhereInput: { // input type
    user?: NexusGenInputs['userWhereInput'] | null; // userWhereInput
    userId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  QueryStacksWhereInput: { // input type
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  QueryTransactionsOrderByInput: { // input type
    date?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  QueryTransactionsWhereInput: { // input type
    user?: NexusGenInputs['userWhereInput'] | null; // userWhereInput
    userId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  StacksListRelationFilter: { // input type
    every?: NexusGenInputs['stacksWhereInput'] | null; // stacksWhereInput
    none?: NexusGenInputs['stacksWhereInput'] | null; // stacksWhereInput
    some?: NexusGenInputs['stacksWhereInput'] | null; // stacksWhereInput
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  TransactionCreateInput: { // input type
    amount: number; // Float!
    date: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    stack: string; // String!
    type: string; // String!
    user: NexusGenInputs['userCreateOneWithoutTransactionsInput']; // userCreateOneWithoutTransactionsInput!
  }
  TransactionCreateManyWithoutUserInput: { // input type
    connect?: NexusGenInputs['TransactionWhereUniqueInput'][] | null; // [TransactionWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['TransactionCreateOrConnectWithoutuserInput'][] | null; // [TransactionCreateOrConnectWithoutuserInput!]
    create?: NexusGenInputs['TransactionCreateWithoutUserInput'][] | null; // [TransactionCreateWithoutUserInput!]
  }
  TransactionCreateOrConnectWithoutuserInput: { // input type
    create: NexusGenInputs['TransactionCreateWithoutUserInput']; // TransactionCreateWithoutUserInput!
    where: NexusGenInputs['TransactionWhereUniqueInput']; // TransactionWhereUniqueInput!
  }
  TransactionCreateWithoutUserInput: { // input type
    amount: number; // Float!
    date: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    stack: string; // String!
    type: string; // String!
  }
  TransactionListRelationFilter: { // input type
    every?: NexusGenInputs['TransactionWhereInput'] | null; // TransactionWhereInput
    none?: NexusGenInputs['TransactionWhereInput'] | null; // TransactionWhereInput
    some?: NexusGenInputs['TransactionWhereInput'] | null; // TransactionWhereInput
  }
  TransactionScalarWhereInput: { // input type
    amount?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    AND?: NexusGenInputs['TransactionScalarWhereInput'][] | null; // [TransactionScalarWhereInput!]
    date?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: NexusGenInputs['TransactionScalarWhereInput'][] | null; // [TransactionScalarWhereInput!]
    OR?: NexusGenInputs['TransactionScalarWhereInput'][] | null; // [TransactionScalarWhereInput!]
    stack?: NexusGenInputs['StringFilter'] | null; // StringFilter
    type?: NexusGenInputs['StringFilter'] | null; // StringFilter
    userId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  TransactionUpdateInput: { // input type
    amount?: NexusGenInputs['FloatFieldUpdateOperationsInput'] | null; // FloatFieldUpdateOperationsInput
    date?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    stack?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    type?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    user?: NexusGenInputs['userUpdateOneRequiredWithoutTransactionsInput'] | null; // userUpdateOneRequiredWithoutTransactionsInput
  }
  TransactionUpdateManyMutationInput: { // input type
    amount?: NexusGenInputs['FloatFieldUpdateOperationsInput'] | null; // FloatFieldUpdateOperationsInput
    date?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    stack?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    type?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  TransactionUpdateManyWithWhereWithoutUserInput: { // input type
    data: NexusGenInputs['TransactionUpdateManyMutationInput']; // TransactionUpdateManyMutationInput!
    where: NexusGenInputs['TransactionScalarWhereInput']; // TransactionScalarWhereInput!
  }
  TransactionUpdateManyWithoutUserInput: { // input type
    connect?: NexusGenInputs['TransactionWhereUniqueInput'][] | null; // [TransactionWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['TransactionCreateOrConnectWithoutuserInput'][] | null; // [TransactionCreateOrConnectWithoutuserInput!]
    create?: NexusGenInputs['TransactionCreateWithoutUserInput'][] | null; // [TransactionCreateWithoutUserInput!]
    delete?: NexusGenInputs['TransactionWhereUniqueInput'][] | null; // [TransactionWhereUniqueInput!]
    deleteMany?: NexusGenInputs['TransactionScalarWhereInput'][] | null; // [TransactionScalarWhereInput!]
    disconnect?: NexusGenInputs['TransactionWhereUniqueInput'][] | null; // [TransactionWhereUniqueInput!]
    set?: NexusGenInputs['TransactionWhereUniqueInput'][] | null; // [TransactionWhereUniqueInput!]
    update?: NexusGenInputs['TransactionUpdateWithWhereUniqueWithoutUserInput'][] | null; // [TransactionUpdateWithWhereUniqueWithoutUserInput!]
    updateMany?: NexusGenInputs['TransactionUpdateManyWithWhereWithoutUserInput'][] | null; // [TransactionUpdateManyWithWhereWithoutUserInput!]
    upsert?: NexusGenInputs['TransactionUpsertWithWhereUniqueWithoutUserInput'][] | null; // [TransactionUpsertWithWhereUniqueWithoutUserInput!]
  }
  TransactionUpdateWithWhereUniqueWithoutUserInput: { // input type
    data: NexusGenInputs['TransactionUpdateWithoutUserInput']; // TransactionUpdateWithoutUserInput!
    where: NexusGenInputs['TransactionWhereUniqueInput']; // TransactionWhereUniqueInput!
  }
  TransactionUpdateWithoutUserInput: { // input type
    amount?: NexusGenInputs['FloatFieldUpdateOperationsInput'] | null; // FloatFieldUpdateOperationsInput
    date?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    description?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    stack?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    type?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  TransactionUpsertWithWhereUniqueWithoutUserInput: { // input type
    create: NexusGenInputs['TransactionCreateWithoutUserInput']; // TransactionCreateWithoutUserInput!
    update: NexusGenInputs['TransactionUpdateWithoutUserInput']; // TransactionUpdateWithoutUserInput!
    where: NexusGenInputs['TransactionWhereUniqueInput']; // TransactionWhereUniqueInput!
  }
  TransactionWhereInput: { // input type
    amount?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    AND?: NexusGenInputs['TransactionWhereInput'][] | null; // [TransactionWhereInput!]
    date?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    description?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: NexusGenInputs['TransactionWhereInput'][] | null; // [TransactionWhereInput!]
    OR?: NexusGenInputs['TransactionWhereInput'][] | null; // [TransactionWhereInput!]
    stack?: NexusGenInputs['StringFilter'] | null; // StringFilter
    type?: NexusGenInputs['StringFilter'] | null; // StringFilter
    user?: NexusGenInputs['userWhereInput'] | null; // userWhereInput
    userId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  TransactionWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  budgetCreateInput: { // input type
    stacks?: NexusGenInputs['stacksCreateManyWithoutBudgetInput'] | null; // stacksCreateManyWithoutBudgetInput
    toBeBudgeted?: number | null; // Float
    total?: number | null; // Float
    user: NexusGenInputs['userCreateOneWithoutBudgetInput']; // userCreateOneWithoutBudgetInput!
  }
  budgetCreateOneWithoutStacksInput: { // input type
    connect?: NexusGenInputs['budgetWhereUniqueInput'] | null; // budgetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['budgetCreateOrConnectWithoutstacksInput'] | null; // budgetCreateOrConnectWithoutstacksInput
    create?: NexusGenInputs['budgetCreateWithoutStacksInput'] | null; // budgetCreateWithoutStacksInput
  }
  budgetCreateOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['budgetWhereUniqueInput'] | null; // budgetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['budgetCreateOrConnectWithoutuserInput'] | null; // budgetCreateOrConnectWithoutuserInput
    create?: NexusGenInputs['budgetCreateWithoutUserInput'] | null; // budgetCreateWithoutUserInput
  }
  budgetCreateOrConnectWithoutstacksInput: { // input type
    create: NexusGenInputs['budgetCreateWithoutStacksInput']; // budgetCreateWithoutStacksInput!
    where: NexusGenInputs['budgetWhereUniqueInput']; // budgetWhereUniqueInput!
  }
  budgetCreateOrConnectWithoutuserInput: { // input type
    create: NexusGenInputs['budgetCreateWithoutUserInput']; // budgetCreateWithoutUserInput!
    where: NexusGenInputs['budgetWhereUniqueInput']; // budgetWhereUniqueInput!
  }
  budgetCreateWithoutStacksInput: { // input type
    toBeBudgeted?: number | null; // Float
    total?: number | null; // Float
    user: NexusGenInputs['userCreateOneWithoutBudgetInput']; // userCreateOneWithoutBudgetInput!
  }
  budgetCreateWithoutUserInput: { // input type
    stacks?: NexusGenInputs['stacksCreateManyWithoutBudgetInput'] | null; // stacksCreateManyWithoutBudgetInput
    toBeBudgeted?: number | null; // Float
    total?: number | null; // Float
  }
  budgetUpdateInput: { // input type
    stacks?: NexusGenInputs['stacksUpdateManyWithoutBudgetInput'] | null; // stacksUpdateManyWithoutBudgetInput
    toBeBudgeted?: NexusGenInputs['NullableFloatFieldUpdateOperationsInput'] | null; // NullableFloatFieldUpdateOperationsInput
    total?: NexusGenInputs['NullableFloatFieldUpdateOperationsInput'] | null; // NullableFloatFieldUpdateOperationsInput
    user?: NexusGenInputs['userUpdateOneRequiredWithoutBudgetInput'] | null; // userUpdateOneRequiredWithoutBudgetInput
  }
  budgetUpdateOneRequiredWithoutStacksInput: { // input type
    connect?: NexusGenInputs['budgetWhereUniqueInput'] | null; // budgetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['budgetCreateOrConnectWithoutstacksInput'] | null; // budgetCreateOrConnectWithoutstacksInput
    create?: NexusGenInputs['budgetCreateWithoutStacksInput'] | null; // budgetCreateWithoutStacksInput
    update?: NexusGenInputs['budgetUpdateWithoutStacksInput'] | null; // budgetUpdateWithoutStacksInput
    upsert?: NexusGenInputs['budgetUpsertWithoutStacksInput'] | null; // budgetUpsertWithoutStacksInput
  }
  budgetUpdateOneWithoutUserInput: { // input type
    connect?: NexusGenInputs['budgetWhereUniqueInput'] | null; // budgetWhereUniqueInput
    connectOrCreate?: NexusGenInputs['budgetCreateOrConnectWithoutuserInput'] | null; // budgetCreateOrConnectWithoutuserInput
    create?: NexusGenInputs['budgetCreateWithoutUserInput'] | null; // budgetCreateWithoutUserInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['budgetUpdateWithoutUserInput'] | null; // budgetUpdateWithoutUserInput
    upsert?: NexusGenInputs['budgetUpsertWithoutUserInput'] | null; // budgetUpsertWithoutUserInput
  }
  budgetUpdateWithoutStacksInput: { // input type
    toBeBudgeted?: NexusGenInputs['NullableFloatFieldUpdateOperationsInput'] | null; // NullableFloatFieldUpdateOperationsInput
    total?: NexusGenInputs['NullableFloatFieldUpdateOperationsInput'] | null; // NullableFloatFieldUpdateOperationsInput
    user?: NexusGenInputs['userUpdateOneRequiredWithoutBudgetInput'] | null; // userUpdateOneRequiredWithoutBudgetInput
  }
  budgetUpdateWithoutUserInput: { // input type
    stacks?: NexusGenInputs['stacksUpdateManyWithoutBudgetInput'] | null; // stacksUpdateManyWithoutBudgetInput
    toBeBudgeted?: NexusGenInputs['NullableFloatFieldUpdateOperationsInput'] | null; // NullableFloatFieldUpdateOperationsInput
    total?: NexusGenInputs['NullableFloatFieldUpdateOperationsInput'] | null; // NullableFloatFieldUpdateOperationsInput
  }
  budgetUpsertWithoutStacksInput: { // input type
    create: NexusGenInputs['budgetCreateWithoutStacksInput']; // budgetCreateWithoutStacksInput!
    update: NexusGenInputs['budgetUpdateWithoutStacksInput']; // budgetUpdateWithoutStacksInput!
  }
  budgetUpsertWithoutUserInput: { // input type
    create: NexusGenInputs['budgetCreateWithoutUserInput']; // budgetCreateWithoutUserInput!
    update: NexusGenInputs['budgetUpdateWithoutUserInput']; // budgetUpdateWithoutUserInput!
  }
  budgetWhereInput: { // input type
    AND?: NexusGenInputs['budgetWhereInput'][] | null; // [budgetWhereInput!]
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: NexusGenInputs['budgetWhereInput'][] | null; // [budgetWhereInput!]
    OR?: NexusGenInputs['budgetWhereInput'][] | null; // [budgetWhereInput!]
    stacks?: NexusGenInputs['StacksListRelationFilter'] | null; // StacksListRelationFilter
    toBeBudgeted?: NexusGenInputs['FloatNullableFilter'] | null; // FloatNullableFilter
    total?: NexusGenInputs['FloatNullableFilter'] | null; // FloatNullableFilter
    user?: NexusGenInputs['userWhereInput'] | null; // userWhereInput
    userId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  budgetWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  stacksCreateInput: { // input type
    amount?: number | null; // Float
    budget: NexusGenInputs['budgetCreateOneWithoutStacksInput']; // budgetCreateOneWithoutStacksInput!
    created_at?: NexusGenScalars['DateTime'] | null; // DateTime
    label: string; // String!
  }
  stacksCreateManyWithoutBudgetInput: { // input type
    connect?: NexusGenInputs['stacksWhereUniqueInput'][] | null; // [stacksWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['stacksCreateOrConnectWithoutbudgetInput'][] | null; // [stacksCreateOrConnectWithoutbudgetInput!]
    create?: NexusGenInputs['stacksCreateWithoutBudgetInput'][] | null; // [stacksCreateWithoutBudgetInput!]
  }
  stacksCreateOrConnectWithoutbudgetInput: { // input type
    create: NexusGenInputs['stacksCreateWithoutBudgetInput']; // stacksCreateWithoutBudgetInput!
    where: NexusGenInputs['stacksWhereUniqueInput']; // stacksWhereUniqueInput!
  }
  stacksCreateWithoutBudgetInput: { // input type
    amount?: number | null; // Float
    created_at?: NexusGenScalars['DateTime'] | null; // DateTime
    label: string; // String!
  }
  stacksOrderByInput: { // input type
    amount?: NexusGenEnums['SortOrder'] | null; // SortOrder
    budgetId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    created_at?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    label?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  stacksScalarWhereInput: { // input type
    amount?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    AND?: NexusGenInputs['stacksScalarWhereInput'][] | null; // [stacksScalarWhereInput!]
    budgetId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    created_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    label?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: NexusGenInputs['stacksScalarWhereInput'][] | null; // [stacksScalarWhereInput!]
    OR?: NexusGenInputs['stacksScalarWhereInput'][] | null; // [stacksScalarWhereInput!]
  }
  stacksUpdateInput: { // input type
    amount?: NexusGenInputs['FloatFieldUpdateOperationsInput'] | null; // FloatFieldUpdateOperationsInput
    budget?: NexusGenInputs['budgetUpdateOneRequiredWithoutStacksInput'] | null; // budgetUpdateOneRequiredWithoutStacksInput
    created_at?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    label?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  stacksUpdateManyMutationInput: { // input type
    amount?: NexusGenInputs['FloatFieldUpdateOperationsInput'] | null; // FloatFieldUpdateOperationsInput
    created_at?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    label?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  stacksUpdateManyWithWhereWithoutBudgetInput: { // input type
    data: NexusGenInputs['stacksUpdateManyMutationInput']; // stacksUpdateManyMutationInput!
    where: NexusGenInputs['stacksScalarWhereInput']; // stacksScalarWhereInput!
  }
  stacksUpdateManyWithoutBudgetInput: { // input type
    connect?: NexusGenInputs['stacksWhereUniqueInput'][] | null; // [stacksWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['stacksCreateOrConnectWithoutbudgetInput'][] | null; // [stacksCreateOrConnectWithoutbudgetInput!]
    create?: NexusGenInputs['stacksCreateWithoutBudgetInput'][] | null; // [stacksCreateWithoutBudgetInput!]
    delete?: NexusGenInputs['stacksWhereUniqueInput'][] | null; // [stacksWhereUniqueInput!]
    deleteMany?: NexusGenInputs['stacksScalarWhereInput'][] | null; // [stacksScalarWhereInput!]
    disconnect?: NexusGenInputs['stacksWhereUniqueInput'][] | null; // [stacksWhereUniqueInput!]
    set?: NexusGenInputs['stacksWhereUniqueInput'][] | null; // [stacksWhereUniqueInput!]
    update?: NexusGenInputs['stacksUpdateWithWhereUniqueWithoutBudgetInput'][] | null; // [stacksUpdateWithWhereUniqueWithoutBudgetInput!]
    updateMany?: NexusGenInputs['stacksUpdateManyWithWhereWithoutBudgetInput'][] | null; // [stacksUpdateManyWithWhereWithoutBudgetInput!]
    upsert?: NexusGenInputs['stacksUpsertWithWhereUniqueWithoutBudgetInput'][] | null; // [stacksUpsertWithWhereUniqueWithoutBudgetInput!]
  }
  stacksUpdateWithWhereUniqueWithoutBudgetInput: { // input type
    data: NexusGenInputs['stacksUpdateWithoutBudgetInput']; // stacksUpdateWithoutBudgetInput!
    where: NexusGenInputs['stacksWhereUniqueInput']; // stacksWhereUniqueInput!
  }
  stacksUpdateWithoutBudgetInput: { // input type
    amount?: NexusGenInputs['FloatFieldUpdateOperationsInput'] | null; // FloatFieldUpdateOperationsInput
    created_at?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    label?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  stacksUpsertWithWhereUniqueWithoutBudgetInput: { // input type
    create: NexusGenInputs['stacksCreateWithoutBudgetInput']; // stacksCreateWithoutBudgetInput!
    update: NexusGenInputs['stacksUpdateWithoutBudgetInput']; // stacksUpdateWithoutBudgetInput!
    where: NexusGenInputs['stacksWhereUniqueInput']; // stacksWhereUniqueInput!
  }
  stacksWhereInput: { // input type
    amount?: NexusGenInputs['FloatFilter'] | null; // FloatFilter
    AND?: NexusGenInputs['stacksWhereInput'][] | null; // [stacksWhereInput!]
    budget?: NexusGenInputs['budgetWhereInput'] | null; // budgetWhereInput
    budgetId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    created_at?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    label?: NexusGenInputs['StringFilter'] | null; // StringFilter
    NOT?: NexusGenInputs['stacksWhereInput'][] | null; // [stacksWhereInput!]
    OR?: NexusGenInputs['stacksWhereInput'][] | null; // [stacksWhereInput!]
  }
  stacksWhereUniqueInput: { // input type
    budgetId_label_idx?: NexusGenInputs['BudgetId_label_idxCompoundUniqueInput'] | null; // BudgetId_label_idxCompoundUniqueInput
    id?: number | null; // Int
  }
  userCreateInput: { // input type
    budget?: NexusGenInputs['budgetCreateOneWithoutUserInput'] | null; // budgetCreateOneWithoutUserInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    emailVerified?: NexusGenScalars['DateTime'] | null; // DateTime
    image?: string | null; // String
    name?: string | null; // String
    transactions?: NexusGenInputs['TransactionCreateManyWithoutUserInput'] | null; // TransactionCreateManyWithoutUserInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  userCreateOneWithoutBudgetInput: { // input type
    connect?: NexusGenInputs['userWhereUniqueInput'] | null; // userWhereUniqueInput
    connectOrCreate?: NexusGenInputs['userCreateOrConnectWithoutbudgetInput'] | null; // userCreateOrConnectWithoutbudgetInput
    create?: NexusGenInputs['userCreateWithoutBudgetInput'] | null; // userCreateWithoutBudgetInput
  }
  userCreateOneWithoutTransactionsInput: { // input type
    connect?: NexusGenInputs['userWhereUniqueInput'] | null; // userWhereUniqueInput
    connectOrCreate?: NexusGenInputs['userCreateOrConnectWithouttransactionsInput'] | null; // userCreateOrConnectWithouttransactionsInput
    create?: NexusGenInputs['userCreateWithoutTransactionsInput'] | null; // userCreateWithoutTransactionsInput
  }
  userCreateOrConnectWithoutbudgetInput: { // input type
    create: NexusGenInputs['userCreateWithoutBudgetInput']; // userCreateWithoutBudgetInput!
    where: NexusGenInputs['userWhereUniqueInput']; // userWhereUniqueInput!
  }
  userCreateOrConnectWithouttransactionsInput: { // input type
    create: NexusGenInputs['userCreateWithoutTransactionsInput']; // userCreateWithoutTransactionsInput!
    where: NexusGenInputs['userWhereUniqueInput']; // userWhereUniqueInput!
  }
  userCreateWithoutBudgetInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    emailVerified?: NexusGenScalars['DateTime'] | null; // DateTime
    image?: string | null; // String
    name?: string | null; // String
    transactions?: NexusGenInputs['TransactionCreateManyWithoutUserInput'] | null; // TransactionCreateManyWithoutUserInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  userCreateWithoutTransactionsInput: { // input type
    budget?: NexusGenInputs['budgetCreateOneWithoutUserInput'] | null; // budgetCreateOneWithoutUserInput
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    email: string; // String!
    emailVerified?: NexusGenScalars['DateTime'] | null; // DateTime
    image?: string | null; // String
    name?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  userUpdateOneRequiredWithoutBudgetInput: { // input type
    connect?: NexusGenInputs['userWhereUniqueInput'] | null; // userWhereUniqueInput
    connectOrCreate?: NexusGenInputs['userCreateOrConnectWithoutbudgetInput'] | null; // userCreateOrConnectWithoutbudgetInput
    create?: NexusGenInputs['userCreateWithoutBudgetInput'] | null; // userCreateWithoutBudgetInput
    update?: NexusGenInputs['userUpdateWithoutBudgetInput'] | null; // userUpdateWithoutBudgetInput
    upsert?: NexusGenInputs['userUpsertWithoutBudgetInput'] | null; // userUpsertWithoutBudgetInput
  }
  userUpdateOneRequiredWithoutTransactionsInput: { // input type
    connect?: NexusGenInputs['userWhereUniqueInput'] | null; // userWhereUniqueInput
    connectOrCreate?: NexusGenInputs['userCreateOrConnectWithouttransactionsInput'] | null; // userCreateOrConnectWithouttransactionsInput
    create?: NexusGenInputs['userCreateWithoutTransactionsInput'] | null; // userCreateWithoutTransactionsInput
    update?: NexusGenInputs['userUpdateWithoutTransactionsInput'] | null; // userUpdateWithoutTransactionsInput
    upsert?: NexusGenInputs['userUpsertWithoutTransactionsInput'] | null; // userUpsertWithoutTransactionsInput
  }
  userUpdateWithoutBudgetInput: { // input type
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    emailVerified?: NexusGenInputs['NullableDateTimeFieldUpdateOperationsInput'] | null; // NullableDateTimeFieldUpdateOperationsInput
    image?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    transactions?: NexusGenInputs['TransactionUpdateManyWithoutUserInput'] | null; // TransactionUpdateManyWithoutUserInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  userUpdateWithoutTransactionsInput: { // input type
    budget?: NexusGenInputs['budgetUpdateOneWithoutUserInput'] | null; // budgetUpdateOneWithoutUserInput
    createdAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
    email?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    emailVerified?: NexusGenInputs['NullableDateTimeFieldUpdateOperationsInput'] | null; // NullableDateTimeFieldUpdateOperationsInput
    image?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    name?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    updatedAt?: NexusGenInputs['DateTimeFieldUpdateOperationsInput'] | null; // DateTimeFieldUpdateOperationsInput
  }
  userUpsertWithoutBudgetInput: { // input type
    create: NexusGenInputs['userCreateWithoutBudgetInput']; // userCreateWithoutBudgetInput!
    update: NexusGenInputs['userUpdateWithoutBudgetInput']; // userUpdateWithoutBudgetInput!
  }
  userUpsertWithoutTransactionsInput: { // input type
    create: NexusGenInputs['userCreateWithoutTransactionsInput']; // userCreateWithoutTransactionsInput!
    update: NexusGenInputs['userUpdateWithoutTransactionsInput']; // userUpdateWithoutTransactionsInput!
  }
  userWhereInput: { // input type
    AND?: NexusGenInputs['userWhereInput'][] | null; // [userWhereInput!]
    budget?: NexusGenInputs['budgetWhereInput'] | null; // budgetWhereInput
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    email?: NexusGenInputs['StringFilter'] | null; // StringFilter
    emailVerified?: NexusGenInputs['DateTimeNullableFilter'] | null; // DateTimeNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    image?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    NOT?: NexusGenInputs['userWhereInput'][] | null; // [userWhereInput!]
    OR?: NexusGenInputs['userWhereInput'][] | null; // [userWhereInput!]
    transactions?: NexusGenInputs['TransactionListRelationFilter'] | null; // TransactionListRelationFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  userWhereUniqueInput: { // input type
    email?: string | null; // String
    id?: number | null; // Int
  }
}

export interface NexusGenEnums {
  QueryMode: "default" | "insensitive"
  SortOrder: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
  Upload: any
}

export interface NexusGenObjects {
  BatchPayload: { // root type
    count: number; // Int!
  }
  Mutation: {};
  Query: {};
  Transaction: { // root type
    amount: number; // Float!
    date: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    id: number; // Int!
    stack: string; // String!
    type: string; // String!
    userId: number; // Int!
  }
  UploadFile: { // root type
    filename?: string | null; // String
    uri?: string | null; // String
  }
  budget: { // root type
    id: number; // Int!
    toBeBudgeted?: number | null; // Float
    total?: number | null; // Float
    userId: number; // Int!
  }
  stacks: { // root type
    amount: number; // Float!
    budgetId: number; // Int!
    created_at: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    label: string; // String!
  }
  user: { // root type
    email: string; // String!
    id: number; // Int!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  BatchPayload: { // field return type
    count: number; // Int!
  }
  Mutation: { // field return type
    createOnebudget: NexusGenRootTypes['budget']; // budget!
    createOnestacks: NexusGenRootTypes['stacks']; // stacks!
    createOneTransaction: NexusGenRootTypes['Transaction']; // Transaction!
    createOneuser: NexusGenRootTypes['user']; // user!
    deleteManyTransaction: NexusGenRootTypes['BatchPayload']; // BatchPayload!
    deleteOnestacks: NexusGenRootTypes['stacks'] | null; // stacks
    updateOnebudget: NexusGenRootTypes['budget'] | null; // budget
    updateOnestacks: NexusGenRootTypes['stacks'] | null; // stacks
    updateOneTransaction: NexusGenRootTypes['Transaction'] | null; // Transaction
    uploadFile: NexusGenRootTypes['UploadFile'] | null; // UploadFile
  }
  Query: { // field return type
    budget: NexusGenRootTypes['budget'] | null; // budget
    budgets: NexusGenRootTypes['budget'][]; // [budget!]!
    stacks: NexusGenRootTypes['stacks'][]; // [stacks!]!
    transaction: NexusGenRootTypes['Transaction'] | null; // Transaction
    transactions: NexusGenRootTypes['Transaction'][]; // [Transaction!]!
    user: NexusGenRootTypes['user'] | null; // user
  }
  Transaction: { // field return type
    amount: number; // Float!
    date: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    id: number; // Int!
    stack: string; // String!
    type: string; // String!
    userId: number; // Int!
  }
  UploadFile: { // field return type
    filename: string | null; // String
    uri: string | null; // String
  }
  budget: { // field return type
    id: number; // Int!
    stacks: NexusGenRootTypes['stacks'][]; // [stacks!]!
    toBeBudgeted: number | null; // Float
    total: number | null; // Float
    userId: number; // Int!
  }
  stacks: { // field return type
    amount: number; // Float!
    budgetId: number; // Int!
    created_at: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    label: string; // String!
  }
  user: { // field return type
    budget: NexusGenRootTypes['budget'] | null; // budget
    email: string; // String!
    id: number; // Int!
    transactions: NexusGenRootTypes['Transaction'][]; // [Transaction!]!
  }
}

export interface NexusGenFieldTypeNames {
  BatchPayload: { // field return type name
    count: 'Int'
  }
  Mutation: { // field return type name
    createOnebudget: 'budget'
    createOnestacks: 'stacks'
    createOneTransaction: 'Transaction'
    createOneuser: 'user'
    deleteManyTransaction: 'BatchPayload'
    deleteOnestacks: 'stacks'
    updateOnebudget: 'budget'
    updateOnestacks: 'stacks'
    updateOneTransaction: 'Transaction'
    uploadFile: 'UploadFile'
  }
  Query: { // field return type name
    budget: 'budget'
    budgets: 'budget'
    stacks: 'stacks'
    transaction: 'Transaction'
    transactions: 'Transaction'
    user: 'user'
  }
  Transaction: { // field return type name
    amount: 'Float'
    date: 'DateTime'
    description: 'String'
    id: 'Int'
    stack: 'String'
    type: 'String'
    userId: 'Int'
  }
  UploadFile: { // field return type name
    filename: 'String'
    uri: 'String'
  }
  budget: { // field return type name
    id: 'Int'
    stacks: 'stacks'
    toBeBudgeted: 'Float'
    total: 'Float'
    userId: 'Int'
  }
  stacks: { // field return type name
    amount: 'Float'
    budgetId: 'Int'
    created_at: 'DateTime'
    id: 'Int'
    label: 'String'
  }
  user: { // field return type name
    budget: 'budget'
    email: 'String'
    id: 'Int'
    transactions: 'Transaction'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOnebudget: { // args
      data: NexusGenInputs['budgetCreateInput']; // budgetCreateInput!
    }
    createOnestacks: { // args
      data: NexusGenInputs['stacksCreateInput']; // stacksCreateInput!
    }
    createOneTransaction: { // args
      data: NexusGenInputs['TransactionCreateInput']; // TransactionCreateInput!
    }
    createOneuser: { // args
      data: NexusGenInputs['userCreateInput']; // userCreateInput!
    }
    deleteManyTransaction: { // args
      where?: NexusGenInputs['TransactionWhereInput'] | null; // TransactionWhereInput
    }
    deleteOnestacks: { // args
      where: NexusGenInputs['stacksWhereUniqueInput']; // stacksWhereUniqueInput!
    }
    updateOnebudget: { // args
      data: NexusGenInputs['budgetUpdateInput']; // budgetUpdateInput!
      where: NexusGenInputs['budgetWhereUniqueInput']; // budgetWhereUniqueInput!
    }
    updateOnestacks: { // args
      data: NexusGenInputs['stacksUpdateInput']; // stacksUpdateInput!
      where: NexusGenInputs['stacksWhereUniqueInput']; // stacksWhereUniqueInput!
    }
    updateOneTransaction: { // args
      data: NexusGenInputs['TransactionUpdateInput']; // TransactionUpdateInput!
      where: NexusGenInputs['TransactionWhereUniqueInput']; // TransactionWhereUniqueInput!
    }
    uploadFile: { // args
      file?: NexusGenScalars['Upload'] | null; // Upload
    }
  }
  Query: {
    budget: { // args
      where: NexusGenInputs['budgetWhereUniqueInput']; // budgetWhereUniqueInput!
    }
    budgets: { // args
      after?: NexusGenInputs['budgetWhereUniqueInput'] | null; // budgetWhereUniqueInput
      before?: NexusGenInputs['budgetWhereUniqueInput'] | null; // budgetWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      where?: NexusGenInputs['QueryBudgetsWhereInput'] | null; // QueryBudgetsWhereInput
    }
    stacks: { // args
      after?: NexusGenInputs['stacksWhereUniqueInput'] | null; // stacksWhereUniqueInput
      before?: NexusGenInputs['stacksWhereUniqueInput'] | null; // stacksWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      where?: NexusGenInputs['QueryStacksWhereInput'] | null; // QueryStacksWhereInput
    }
    transaction: { // args
      where: NexusGenInputs['TransactionWhereUniqueInput']; // TransactionWhereUniqueInput!
    }
    transactions: { // args
      after?: NexusGenInputs['TransactionWhereUniqueInput'] | null; // TransactionWhereUniqueInput
      before?: NexusGenInputs['TransactionWhereUniqueInput'] | null; // TransactionWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['QueryTransactionsOrderByInput'][] | null; // [QueryTransactionsOrderByInput!]
      where?: NexusGenInputs['QueryTransactionsWhereInput'] | null; // QueryTransactionsWhereInput
    }
    user: { // args
      where: NexusGenInputs['userWhereUniqueInput']; // userWhereUniqueInput!
    }
  }
  budget: {
    stacks: { // args
      after?: NexusGenInputs['stacksWhereUniqueInput'] | null; // stacksWhereUniqueInput
      before?: NexusGenInputs['stacksWhereUniqueInput'] | null; // stacksWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['stacksOrderByInput'][] | null; // [stacksOrderByInput!]
    }
  }
  user: {
    transactions: { // args
      after?: NexusGenInputs['TransactionWhereUniqueInput'] | null; // TransactionWhereUniqueInput
      before?: NexusGenInputs['TransactionWhereUniqueInput'] | null; // TransactionWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[]
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[]
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[]
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean
  }
}